"""
KIS Auto Trading - KOSPI 100 Investment Universe
한국거래소(KRX) KOSPI 100 지수 구성 대표 대형 우량주 100종목 정의
"""
from typing import List, Dict

KOSPI_100_STOCKS: List[Dict[str, str]] = [
    {"code": "005930", "name": "삼성전자", "market": "KOSPI"},
    {"code": "000660", "name": "SK하이닉스", "market": "KOSPI"},
    {"code": "373220", "name": "LG에너지솔루션", "market": "KOSPI"},
    {"code": "207940", "name": "삼성바이오로직스", "market": "KOSPI"},
    {"code": "005380", "name": "현대차", "market": "KOSPI"},
    {"code": "000270", "name": "기아", "market": "KOSPI"},
    {"code": "068270", "name": "셀트리온", "market": "KOSPI"},
    {"code": "035420", "name": "NAVER", "market": "KOSPI"},
    {"code": "105560", "name": "KB금융", "market": "KOSPI"},
    {"code": "055550", "name": "신한지주", "market": "KOSPI"},
    {"code": "005490", "name": "POSCO홀딩스", "market": "KOSPI"},
    {"code": "012330", "name": "현대모비스", "market": "KOSPI"},
    {"code": "006400", "name": "삼성SDI", "market": "KOSPI"},
    {"code": "051910", "name": "LG화학", "market": "KOSPI"},
    {"code": "028260", "name": "삼성물산", "market": "KOSPI"},
    {"code": "086790", "name": "하나금융지주", "market": "KOSPI"},
    {"code": "035720", "name": "카카오", "market": "KOSPI"},
    {"code": "010130", "name": "고려아연", "market": "KOSPI"},
    {"code": "003670", "name": "포스코퓨처엠", "market": "KOSPI"},
    {"code": "032830", "name": "삼성생명", "market": "KOSPI"},
    {"code": "012450", "name": "한화에어로스페이스", "market": "KOSPI"},
    {"code": "011200", "name": "HMM", "market": "KOSPI"},
    {"code": "066570", "name": "LG전자", "market": "KOSPI"},
    {"code": "009150", "name": "삼성전기", "market": "KOSPI"},
    {"code": "010950", "name": "S-Oil", "market": "KOSPI"},
    {"code": "034020", "name": "두산에너빌리티", "market": "KOSPI"},
    {"code": "018260", "name": "삼성에스디에스", "market": "KOSPI"},
    {"code": "003550", "name": "LG", "market": "KOSPI"},
    {"code": "033780", "name": "KT&G", "market": "KOSPI"},
    {"code": "000810", "name": "삼성화재", "market": "KOSPI"},
    {"code": "017670", "name": "SK텔레콤", "market": "KOSPI"},
    {"code": "030200", "name": "KT", "market": "KOSPI"},
    {"code": "090430", "name": "아모레퍼시픽", "market": "KOSPI"},
    {"code": "015760", "name": "한국전력", "market": "KOSPI"},
    {"code": "024110", "name": "기업은행", "market": "KOSPI"},
    {"code": "316140", "name": "우리금융지주", "market": "KOSPI"},
    {"code": "000100", "name": "유한양행", "market": "KOSPI"},
    {"code": "071050", "name": "한국금융지주", "market": "KOSPI"},
    {"code": "003490", "name": "대한항공", "market": "KOSPI"},
    {"code": "034730", "name": "SK", "market": "KOSPI"},
    {"code": "096770", "name": "SK이노베이션", "market": "KOSPI"},
    {"code": "326030", "name": "SK바이오팜", "market": "KOSPI"},
    {"code": "329180", "name": "HD현대중공업", "market": "KOSPI"},
    {"code": "042660", "name": "한화오션", "market": "KOSPI"},
    {"code": "010140", "name": "삼성중공업", "market": "KOSPI"},
    {"code": "047810", "name": "한국항공우주", "market": "KOSPI"},
    {"code": "086280", "name": "현대글로비스", "market": "KOSPI"},
    {"code": "042700", "name": "한미반도체", "market": "KOSPI"},
    {"code": "259960", "name": "크래프톤", "market": "KOSPI"},
    {"code": "352820", "name": "하이브", "market": "KOSPI"},
    {"code": "000080", "name": "하이트진로", "market": "KOSPI"},
    {"code": "000990", "name": "DB하이텍", "market": "KOSPI"},
    {"code": "004020", "name": "현대제철", "market": "KOSPI"},
    {"code": "005420", "name": "코스모화학", "market": "KOSPI"},
    {"code": "006800", "name": "미래에셋증권", "market": "KOSPI"},
    {"code": "011070", "name": "LG이노텍", "market": "KOSPI"},
    {"code": "034220", "name": "LG디스플레이", "market": "KOSPI"},
    {"code": "036570", "name": "엔씨소프트", "market": "KOSPI"},
    {"code": "039490", "name": "키움증권", "market": "KOSPI"},
    {"code": "047050", "name": "포스코인터내셔널", "market": "KOSPI"},
    {"code": "051900", "name": "LG생활건강", "market": "KOSPI"},
    {"code": "064350", "name": "현대로템", "market": "KOSPI"},
    {"code": "097950", "name": "CJ제일제당", "market": "KOSPI"},
    {"code": "128940", "name": "한미약품", "market": "KOSPI"},
    {"code": "138040", "name": "메리츠금융지주", "market": "KOSPI"},
    {"code": "251270", "name": "넷마블", "market": "KOSPI"},
    {"code": "267260", "name": "HD현대일렉트릭", "market": "KOSPI"},
    {"code": "302440", "name": "SK바이오사이언스", "market": "KOSPI"},
    {"code": "450080", "name": "에코프로머티", "market": "KOSPI"},
    {"code": "454910", "name": "두산로보틱스", "market": "KOSPI"},
    {"code": "009540", "name": "HD한국조선해양", "market": "KOSPI"},
    {"code": "298040", "name": "효성중공업", "market": "KOSPI"},
    {"code": "402340", "name": "SK스퀘어", "market": "KOSPI"},
    {"code": "009830", "name": "한화솔루션", "market": "KOSPI"},
    {"code": "021240", "name": "코웨이", "market": "KOSPI"},
    {"code": "000120", "name": "CJ대한통운", "market": "KOSPI"},
    {"code": "001040", "name": "CJ", "market": "KOSPI"},
    {"code": "078930", "name": "GS", "market": "KOSPI"},
    {"code": "011170", "name": "롯데케미칼", "market": "KOSPI"},
    {"code": "004170", "name": "신세계", "market": "KOSPI"},
    {"code": "000720", "name": "현대건설", "market": "KOSPI"},
    {"code": "005830", "name": "DB손해보험", "market": "KOSPI"},
    {"code": "001450", "name": "현대해상", "market": "KOSPI"},
    {"code": "004990", "name": "롯데지주", "market": "KOSPI"},
    {"code": "029780", "name": "삼성카드", "market": "KOSPI"},
    {"code": "036460", "name": "한국가스공사", "market": "KOSPI"},
    {"code": "079550", "name": "LIG넥스원", "market": "KOSPI"},
    {"code": "011780", "name": "금호석유", "market": "KOSPI"},
    {"code": "012750", "name": "에스원", "market": "KOSPI"},
    {"code": "004370", "name": "농심", "market": "KOSPI"},
    {"code": "271560", "name": "오리온", "market": "KOSPI"},
    {"code": "008770", "name": "호텔신라", "market": "KOSPI"},
    {"code": "030000", "name": "제일기획", "market": "KOSPI"},
    {"code": "005940", "name": "NH투자증권", "market": "KOSPI"},
    {"code": "014680", "name": "한솔케미칼", "market": "KOSPI"},
    {"code": "241560", "name": "두산밥캣", "market": "KOSPI"},
    {"code": "007070", "name": "GS리테일", "market": "KOSPI"},
    {"code": "002790", "name": "아모레G", "market": "KOSPI"},
    {"code": "006260", "name": "LS", "market": "KOSPI"},
    {"code": "000150", "name": "두산", "market": "KOSPI"}
]

def get_kospi100_universe() -> List[Dict[str, str]]:
    """KOSPI 100 대형 우량주 유니버스 목록 반환"""
    return list(KOSPI_100_STOCKS)
